const Images = {
  Logo: "./images/JayLogo.png",
  MainImage: "./images/MainImage.jpg",
  Patriotic: "./images/Patriotic.jpg",
  Circulam: "./images/Circulam.jpg",
  Lab: "./images/lab.jpg",
  Mind: "./images/minds.png",
  Patriotism: "./images/patriotism.png",
  Reason: "./images/reason.png",
  Thinking: "./images/thinking.png",
  Brilliance: "./images/brilliance.png",
  Diversity: "./images/diversity.png",
  Music: "./images/music.png",
  Possibilities: "./images/possibilities.png",
  Rhythms: "./images/rhythms.png",
  Spirit: "./images/spirit.png",
  Safety: "./images/safety.webp",
  Pathway3: "./images/pathway3.png",
  Pathway4: "./images/pathway4.png",
  Pathway1: "./images/pathway1.webp",
  Pathway2: "./images/pathway2.webp",
  AminOfiice: "./images/adminOffice.webp",
  LoginBg: ",/images/logo26.jpg",
};
export default Images;
